export const EAuthErrors = {
	NOT_AUTHORIZED_YET: "NOT_AUTHORIZED_YET",
	ALREADY_AUTHORIZED: "ALREADY_AUTHORIZED",
	WRONG_PASSWORD: "WRONG_PASSWORD",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	USER_LOGGED_OUT: "USER_LOGGED_OUT",
	USER_INVALID_TOKEN: "USER_INVALID_TOKEN",
} as const;
